version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres-realtime
    environment:
      POSTGRES_DB: realtime_orders
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: realtime-app
    ports:
      - "3000:3000"
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: realtime_orders
      DB_USER: postgres
      DB_PASSWORD: password
      PORT: 3000
      WS_PORT: 8080
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm run setup-db && npm start"

volumes:
  postgres_data:
